import {
  detectAider,
  detectAnthropicMessages,
  detectClaudeCode,
  detectCodex,
  detectCursor,
  detectGenericJsonChat,
  detectMarkdownTranscript,
  detectOpenAIChat,
  detectPi,
  neverAutoDetect,
  normalizeAnthropicMessagesSession,
  normalizeClaudeCodeSession,
  normalizeCodexSession,
  normalizeCursorSession,
  normalizeGenericJsonSession,
  normalizeMarkdownTranscriptSession,
  normalizeOpenAIChatSession,
  normalizePiSession,
  type SourceAdapter,
} from "./normalize.ts";

export const ADAPTERS: SourceAdapter[] = [
  {
    source: "pi",
    sourceFormat: "pi-session-jsonl",
    defaultAgent: "pi",
    detect: detectPi,
    normalize: normalizePiSession,
  },
  {
    source: "claude-code",
    sourceFormat: "claude-code-jsonl",
    defaultAgent: "claude-code",
    detect: detectClaudeCode,
    normalize: normalizeClaudeCodeSession,
  },
  {
    source: "codex",
    sourceFormat: "codex-rollout-jsonl",
    defaultAgent: "codex",
    detect: detectCodex,
    normalize: normalizeCodexSession,
  },
  {
    source: "cursor",
    sourceFormat: "cursor-agent-transcript-jsonl",
    defaultAgent: "cursor",
    detect: detectCursor,
    normalize: normalizeCursorSession,
  },
  {
    source: "anthropic-messages",
    sourceFormat: "anthropic-messages-jsonl",
    defaultAgent: "anthropic-compatible",
    detect: detectAnthropicMessages,
    normalize: normalizeAnthropicMessagesSession,
  },
  {
    source: "opencode",
    sourceFormat: "opencode-openai-compatible-jsonl",
    defaultAgent: "opencode",
    detect: neverAutoDetect,
    normalize: normalizeOpenAIChatSession,
  },
  {
    source: "continue",
    sourceFormat: "continue-openai-compatible-jsonl",
    defaultAgent: "continue",
    detect: neverAutoDetect,
    normalize: normalizeOpenAIChatSession,
  },
  {
    source: "goose",
    sourceFormat: "goose-openai-compatible-jsonl",
    defaultAgent: "goose",
    detect: neverAutoDetect,
    normalize: normalizeOpenAIChatSession,
  },
  {
    source: "openai-chat",
    sourceFormat: "openai-chat-jsonl",
    defaultAgent: "openai-compatible",
    detect: detectOpenAIChat,
    normalize: normalizeOpenAIChatSession,
  },
  {
    source: "generic-json",
    sourceFormat: "generic-json-chat",
    defaultAgent: "generic-json",
    detect: detectGenericJsonChat,
    normalize: normalizeGenericJsonSession,
  },
  {
    source: "aider",
    sourceFormat: "aider-markdown-history",
    defaultAgent: "aider",
    detect: detectAider,
    normalize: normalizeMarkdownTranscriptSession,
  },
  {
    source: "markdown-transcript",
    sourceFormat: "markdown-transcript",
    defaultAgent: "markdown-transcript",
    detect: detectMarkdownTranscript,
    normalize: normalizeMarkdownTranscriptSession,
  },
];
